"""Backward-compat shim. The real module is ``app.core.config``.

Kept so callers like ``alembic/env.py`` and ``evaluation/evaluate.py``
that pre-date the modular layout can keep doing ``import config``.
"""

from app.core.config import *  # noqa: F401,F403
from app.core import config as _config

# Re-export public attributes explicitly so static analysers see them.
ENVIRONMENT = _config.ENVIRONMENT
LOG_LEVEL = _config.LOG_LEVEL
ALLOWED_ORIGINS = _config.ALLOWED_ORIGINS
DATABASE_URL = _config.DATABASE_URL
STORAGE_DIR = _config.STORAGE_DIR
MAX_FILE_SIZE = _config.MAX_FILE_SIZE
ALLOWED_EXTENSIONS = _config.ALLOWED_EXTENSIONS
CHUNK_SIZE = _config.CHUNK_SIZE
CHUNK_OVERLAP = _config.CHUNK_OVERLAP
EMBEDDING_MODEL = _config.EMBEDDING_MODEL
EMBEDDING_DIMENSIONS = _config.EMBEDDING_DIMENSIONS
CHROMA_PERSIST_DIRECTORY = _config.CHROMA_PERSIST_DIRECTORY
CHROMA_COLLECTION_NAME = _config.CHROMA_COLLECTION_NAME
TOP_K = _config.TOP_K
SIMILARITY_THRESHOLD = _config.SIMILARITY_THRESHOLD
MAX_CONTEXT_LENGTH = _config.MAX_CONTEXT_LENGTH
CHAT_HISTORY_MESSAGE_LIMIT = _config.CHAT_HISTORY_MESSAGE_LIMIT
EVAL_TOP_K = _config.EVAL_TOP_K
EVAL_DATASET_PATH = _config.EVAL_DATASET_PATH
EVAL_OUTPUT_PATH = _config.EVAL_OUTPUT_PATH
EVAL_USE_LLM_JUDGE = _config.EVAL_USE_LLM_JUDGE
EVAL_LLM_JUDGE_MODEL = _config.EVAL_LLM_JUDGE_MODEL
LLM_PROVIDER = _config.LLM_PROVIDER
LLM_MODEL = _config.LLM_MODEL
GROQ_API_KEY = _config.GROQ_API_KEY
JWT_SECRET_KEY = _config.JWT_SECRET_KEY
JWT_ALGORITHM = _config.JWT_ALGORITHM
ACCESS_TOKEN_EXPIRE_MINUTES = _config.ACCESS_TOKEN_EXPIRE_MINUTES
